//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegCiptvAccounts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lista
    {
        public int Id { get; set; }
        public string Server { get; set; }
        public string Login { get; set; }
        public string Pass { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
